#ifndef NUTRITONALTYPES
#define NUTRITONALTYPES

enum NutritionalTypes{
    KCAL, PROTEINS, FAT, CARBOHYDRATES,
    ROUGHAGE, SODIUM, POTASSIUM, CALCIUM,
    PHOSPHORUS, IRON, MAGNESIUM, VITAMIN_A,
    VITAMIN_E, VITAMIN_C
};

#endif // NUTRITONALTYPES

